services:
  grafana-otel:
    image: grafana/otel-lgtm:latest
    container_name: grafana-otel
    restart: always
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    ports:
      - "3000:3000"
      - "4317-4318:4317-4318"
    volumes:
      - ./grafana/plugins:/data/grafana/plugins
      - ./grafana/run-grafana.sh:/otel-lgtm/run-grafana.sh
      - grafana_data:/data

volumes:
  grafana_data: